# Generated by Django 3.1.7 on 2021-04-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_product_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
