# Generated by Django 3.1.7 on 2021-04-08 05:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210407_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stand_id',
            field=models.IntegerField(default=uuid.UUID('18fb1e1e-f910-4a41-b95a-014238ecf867'), null=True),
        ),
    ]
