# Generated by Django 3.1.7 on 2021-04-08 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_product_stand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=uuid.UUID('23c2b4bb-982a-11eb-a9d9-5c93a2dec3b9')),
        ),
        migrations.AlterField(
            model_name='product',
            name='stand_id',
            field=models.IntegerField(default=uuid.UUID('354ebb79-da2f-41bd-b3f2-13ff0a27a11c'), null=True),
        ),
    ]
