# Generated by Django 3.1.7 on 2021-04-08 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210407_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=uuid.UUID('31892604-982b-11eb-9b27-5c93a2dec3b9')),
        ),
        migrations.AlterField(
            model_name='product',
            name='stand_id',
            field=models.IntegerField(default=uuid.UUID('16fd5992-3276-49e3-8f43-d8082b692dd0'), null=True),
        ),
    ]
