# Generated by Django 3.1.7 on 2021-04-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210407_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stand_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
